import React from 'react';

export default function CertificateCard({ src, originalPrompt, enhancedPrompt, label }) {
  const now  = new Date();
  const date = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const time = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

  return (
    <div className="cert-wrapper">
      <div className="cert-border">
        <div className="cert-inner">
          <div className="cert-header">
            <span className="cert-logo">🍐</span>
            <div>
              <div className="cert-title">Pear Media</div>
              <div className="cert-subtitle">AI Creative Studio — Certificate of Generation</div>
            </div>
          </div>
          <div className="cert-divider" />
          <div className="cert-image-wrap">
            <img src={src} alt="Generated" className="cert-image" />
          </div>
          <div className="cert-divider" />
          <div className="cert-fields">
            {originalPrompt && (
              <div className="cert-field">
                <span className="cert-field-label">Original Prompt</span>
                <span className="cert-field-value">{originalPrompt}</span>
              </div>
            )}
            <div className="cert-field">
              <span className="cert-field-label">{label || 'Enhanced Prompt'}</span>
              <span className="cert-field-value">{enhancedPrompt}</span>
            </div>
          </div>
          <div className="cert-divider" />
          <div className="cert-footer">
            <div className="cert-meta">
              <span>🤖 Generated by FLUX.1-schnell</span>
              <span>📅 {date} at {time}</span>
            </div>
            <a className="cert-download" href={src} download="pear-media-output.png">
              ⬇️ Download
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
